//tealium universal tag - utag.1375 ut4.0.201711221909, Copyright 2017 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"order_total_usd":"value","oc_customer_type":"cusType","product_name":"productName","product_price_usd":"priceUSD"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={'ret_base_url':'//secure.adnxs.com/seg','conv_base_url':'//secure.adnxs.com/px','adCode':'','member_id':'1661','id':'','seg':'','value':'',//@@order_total_usd@@
'cusType':'',//@@oc_customer_type@@
'productName':'',//@@product_name@@
'priceUSD':''//@@product_price_usd@@
};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(window.tagUtils.contains(b.app_name,'sales')){u.data.adCode='GD_'+b['dom.domain']+'_'+b['dom.pathname'];u.loader({'type':'img','src':u.data.ret_base_url+'?member_id='+u.data.member_id+'&add_code='+u.data.adCode})}else{if(window.tagUtils.equals(b.page_type,'orderconfirmation')){switch(b['cp.market'].toString()){case'pt-BR':u.data.id='750400';u.data.seg='6061662';break;case'es-ES':u.data.id='746003';u.data.seg='5980170';break;case'en-IN':u.data.id='764485';u.data.seg='6352003';break;case'mr-IN':u.data.id='764485';u.data.seg='6352003';break;case'hi-IN':u.data.id='764485';u.data.seg='6352003';break;case'ta-IN':u.data.id='764485';u.data.seg='6352003';break;case'en-GB':u.data.id='783825';u.data.seg='7011347';break;default:break;}
u.loader({'type':'img','src':u.data.conv_base_url+'?id='+u.data.id+'&seg='+u.data.seg+
'&value='+u.data.value+'&other='+u.data.cusType+'&other='+u.data.productName+
'&other='+u.data.priceUSD});}}
}};utag.o[loader].loader.LOAD(id);})("1375","godaddy.godaddy");}catch(error){utag.DB(error);}
