//tealium universal tag - utag.1389 ut4.0.201801112211, Copyright 2018 Tealium.com Inc. All Rights Reserved.
window.dataLayer=window.dataLayer||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}
if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}
if(o.id){b.id=o.id;}
if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}
l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={'event_base_url':'//www.googletagmanager.com/gtag/js?id=AW-1069554140',"aw_base_url":"//googleads.g.doubleclick.net/pagead/viewthroughconversion/1069554140","dc_base_url":"//ad.doubleclick.net/ddm/activity/src=8316070",'value':''};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','AW-1069554140');gtag('config','DC-8316070');if(window.tagUtils.contains(b.app_name,"sales")){gtag("event","conversion",{send_to:"DC-8316070/retar0/ret-page+standard",language:"en",u13:b.session_id,});}
if(window.tagUtils.equals(b.page_type,"orderconfirmation")){u.data.value=b.order_total_usd||b._ctotal||"";if(window.tagUtils.equals(b.oc_customer_type,"new")){gtag("event","conversion",{send_to:"AW-1069554140/rpNvCOKV_1UQ3LOA_gM",value:u.data.value,currency:"USD",language:"en"});gtag("event","purchase",{send_to:"DC-8316070/gdconv/godad0+transactions",value:u.data.value,currency:"USD",transaction_id:b.order_id,u1:b.oc_customer_type,u2:b.order_total,u3:b.order_total_usd,u4:b.order_total_new,u5:b.order_total_new_usd,u6:b.currency_usd,u7:b.product_category_name,u8:b.product_count,u9:b.product_id,u10:b.product_name,u11:b.product_price,u12:b.product_price_usd,u13:b.session_id,ord:b.cachebuster});}else{gtag("event","conversion",{send_to:"AW-1069554140/h-DhCMzP1wcQ3LOA_gM",value:u.data.value,currency:"USD",language:"en"});gtag("event","purchase",{send_to:"DC-8316070/gdconv/conordec+transactions",value:u.data.value,currency:"USD",transaction_id:b.order_id,u1:b.oc_customer_type,u2:b.order_total,u3:b.order_total_usd,u4:b.order_total_new,u5:b.order_total_new_usd,u6:b.currency_usd,u7:b.product_category_name,u8:b.product_count,u9:b.product_id,u10:b.product_name,u11:b.product_price,u12:b.product_price_usd,u13:b.session_id,ord:b.cachebuster});}}
if(window.tagUtils.isDefined(b.goCentral_activation)){gtag("event","conversion",{send_to:"AW-1069554140/XuLqCNy-im0Q3LOA_gM",language:"en"});gtag("event","purchase",{send_to:"DC-8316070/gdconv/ft-gcwsb+transactions",language:"en",value:0,transaction_id:b.order_id,u13:b.session_id,ord:b.cachebuster});}
if(window.tagUtils.equals(b.app_name,"webpro")&&window.tagUtils.isDefined(b.pro_signup)){gtag("event","conversion",{send_to:"AW-1069554140/y2hjCP-hp1sQ3LOA_gM",language:"en"});gtag("event","conversion",{send_to:"DC-8316070/conve0/godad0+standard",u13:b.session_id,language:"en"});}
if(window.tagUtils.contains(b["dom.domain"],"smartline.godaddy.com")){gtag("event","conversion",{send_to:"AW-1069554140/bg2SCNbS5HAQ3LOA_gM",language:"en"});gtag("event","purchase",{send_to:"DC-8316070/gdconv/ft-smtln+transactions",language:"en",value:0,transaction_id:b.order_id,u13:b.session_id,ord:b.cachebuster});}
if(window.tagUtils.contains(b["dom.pathname"],"/business/office-365/office-business/contact-us")&&window.tagUtils.equals(b.pws_event,"submit")){gtag("event","conversion",{send_to:"DC-8316070/conve0/godad00+standard",u13:b.session_id,language:"en"});}
if(window.tagUtils.equals(b.app_name,'cart')&&window.tagUtils.equals(b.mc,'true')){u.loader({"type":"img","src":u.data.aw_base_url+"?guid=ON&script=0"});u.loader({"type":"img","src":u.data.dc_base_url+";type=retar0;cat=ret-page;u9="+b.product_id+";u13="+b.session_id+";dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;ord=1?"});}else{u.loader({"type":"script","src":u.data.event_base_url,"cb":u.loader_cb,"loc":"script","id":'utag_1389'});}
}};utag.o[loader].loader.LOAD(id);})("1389","godaddy.godaddy");}catch(error){utag.DB(error);}
